apiVersion: v1
data:
  token: eG94Yi1ZT1VSLVRPS0VO
kind: Secret
metadata:
  name: googlechat-bot-token
  namespace: flux-system
type: Opaque
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: googlechat-bot
  namespace: flux-system
spec:
  type: googlechat
  channel: general
  address: https://chat.googleapis.com/v1/spaces/AAAAvumIubo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=TMtHYQE-aHy0oKH2vhbAFLJzzwCDphYbx0Eiag4PoYQ
  secretRef:
    name: googlechat-bot-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: my-gchat-notification
  namespace: flux-system
spec:
  summary: "Sync Messages"
  eventMetadata:
    env: "TBC"
  providerRef:
    name: googlechat-bot
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'